create table
  public.recipe (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    constraint recipe_pkey primary key (id)
  ) tablespace pg_default;