create table
  public.recipe_ingredient (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    recipe_id bigint null,
    ingredient_id bigint null,
    amount text null,
    constraint recipe_ingredient_pkey primary key (id),
    constraint public_recipe_ingredient_ingredient_id_fkey foreign key (ingredient_id) references ingredient (id),
    constraint public_recipe_ingredient_recipe_id_fkey foreign key (recipe_id) references recipe (id)
  ) tablespace pg_default;