create table
  public.ingredient (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text null,
    constraint ingredient_pkey primary key (id)
  ) tablespace pg_default;